### PR TITLE
Update use of objectweb.asm types.

### PR DESCRIPTION
**Pull request by tkoeppe**

### CODE REVIEW

**Comment by headius** [comment]
Looks good to me.

**Comment by ebourg** [comment]
Thank you

**Comment by tkoeppe** [comment]
@ebourg :-) Does it work for you now?

**Comment by ebourg** [comment]
I have to admit, I don't remember why I needed this ;)

**Comment by ebourg** [comment]
Actually, this error occured when I upgraded ASM in Debian, I had to patch jitescript to work around the issue.

https://salsa.debian.org/java-team/jitescript/-/blob/master/debian/patches/01-asm-compatibility.patch

I haven't tested the new version but it looks good.

**Comment by tkoeppe** [comment]
Yes, I believe that was our situation too. We simply had a local (new) version of ASM that wouldn't work with jitescript 0.4.1.

**Pull request merged**
